### ISSUE TITLE
Not auto-detecting komodo release version

### ISSUE THREAD

**Issue by dotfloat** [equinor/komodoenv#21]
```
(bleeding-py36) [zom@st-linapp1192 ~]$ komodoenv kenv
/prog/res/komodo/stable-py36
/prog/res/komodo/testing-py36
/prog/res/komodo/unstable-py36
/prog/res/komodo/bleeding-py36
Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py36-rhel7/root/bin/komodoenv", line 8, in <module>
    sys.exit(main())
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/komodoenv/__main__.py", line 157, in main
    args = parse_args(args)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/komodoenv/__main__.py", line 126, in parse_args
    args.release = detect_rhel(args.release)
  File "/prog/res/komodo/bleeding-py36-rhel7/root/lib/python3.6/site-packages/komodoenv/__main__.py", line 75, in detect_rhel
    if not komodo_prefix.is_dir():
AttributeError: 'NoneType' object has no attribute 'is_dir'
```

**Comment by berland** [comment]
Upvote!
