### ISSUE TITLE
virtualenv from bleeding-py36 may conflict with ~/.local/python3.6/site-packages/virtualenv

### ISSUE THREAD

**Issue by dotfloat** [equinor/komodoenv#7]
Steps to reproduce:
1. `pip install --user --upgrade 'virtualenv<20'`
2. `source /prog/res/komodo/bleeding-py36/enable`
3. `komodoenv -rstable-py36 kenv`

Observe error:
```
KomodoType.SHIM [3, 6, 9, 'final', 0]
Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py36/root/libexec/komodoenv", line 11, in <module>
    sys.exit(main())
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/komodoenv/main.py", line 59, in main
    create(ctx)
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/komodoenv/creator.py", line 168, in create
    create_virtualenv(ctx)
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/site-packages/komodoenv/creator.py", line 101, in create_virtualenv
    str(ctx.dstpath / "root"),
  File "/private/zom/.local/lib/python3.6/site-packages/virtualenv/run/__init__.py", line 24, in cli_run
    session = session_via_cli(args, options)
  File "/private/zom/.local/lib/python3.6/site-packages/virtualenv/run/__init__.py", line 32, in session_via_cli
    parser, elements = build_parser(args, options)
  File "/private/zom/.local/lib/python3.6/site-packages/virtualenv/run/__init__.py", line 60, in build_parser
    SeederSelector(interpreter, parser),
  File "/private/zom/.local/lib/python3.6/site-packages/virtualenv/run/plugin/seeders.py", line 8, in __init__
    possible = self.options("virtualenv.seed")
  File "/private/zom/.local/lib/python3.6/site-packages/virtualenv/run/plugin/base.py", line 39, in options
    cls._OPTIONS = cls.entry_points_for(key)
  File "/private/zom/.local/lib/python3.6/site-packages/virtualenv/run/plugin/base.py", line 18, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/private/zom/.local/lib/python3.6/site-packages/virtualenv/run/plugin/base.py", line 18, in <genexpr>
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/private/zom/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/prog/res/komodo/bleeding-py36/root/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
```

Notice how it's finding my local virtualenv. If I run with `export PYTHONNOUSERSITE=1` then a komodoenv is created as expected.

**Comment by dotfloat** [comment]
No longer using `virtualenv`, closing.
