### ISSUE TITLE
Nightly tests fail 

### ISSUE THREAD

**Issue by sondreso** [equinor/komodoenv#77]
**Describe the bug**
Running `komodoenv --root /prog/res/komodo -r bleeding-py38-rhel7 --no-update --force test-kenv`
gives the following error:
```
Traceback (most recent call last):
  File "/private/sonso/test-kenv/root/bin/komodoenv-update", line 496, in <module>
    main()
  File "/private/sonso/test-kenv/root/bin/komodoenv-update", line 490, in main
    create_pth(config, srcpath, dstpath)
  File "/private/sonso/test-kenv/root/bin/komodoenv-update", line 417, in create_pth
    old_style_pth.unlink(missing_ok=True)
TypeError: unlink() got an unexpected keyword argument 'missing_ok'
Traceback (most recent call last):
  File "/prog/res/komodo/bleeding-py38-rhel7/root/bin/komodoenv", line 8, in <module>
    sys.exit(main())
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/komodoenv/__main__.py", line 227, in main
    creator.create()
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/komodoenv/creator.py", line 142, in create
    self.run("root/bin/komodoenv-update")
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/komodoenv/creator.py", line 77, in run
    subprocess.check_output([str(self.dstpath / path)])
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/sonso/test-kenv/root/bin/komodoenv-update']' returned non-zero exit status 1.
```

**To Reproduce**
See above

**Expected behavior**
Not crash

**Screenshots**
N/A

**Additional context**
https://github.com/equinor/komodo-releases/actions/runs/9574064333/job/26397341066

**Comment by sondreso** [comment]
Probably related to this commit: https://github.com/equinor/komodoenv/commit/2f51665f2f4e45d3c3ec983634f9153d0b2fdd7a

**Comment by sondreso** [comment]
See also: https://github.com/equinor/komodo-releases/issues/5970

**Comment by andreas-el** [comment]
Is this executed using an old python version?
